version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:5000"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
